### ISSUE TITLE
Cyberghost can not be installed

### ISSUE THREAD

**Issue by Cyb10101** [Cyb10101/notes#2]
See todo: 2019-02-04 Cyberghost can not be installed

[System/Linux/VPN.md](System/Linux/VPN.md)

```bash
# Also run in the Cyberghost installation script:
sudo cyberghostvpn --setup

Do you want to override the original configuration file? [Y/n]: y
Setup account ...
Enter CyberGhost username and press [ENTER]: **********
Enter CyberGhost password and press [ENTER]: **********
Traceback (most recent call last):
File "cyberghostvpn.py", line 761, in <module>
File "cyberghostvpn.py", line 370, in main
File "cyberghostvpn.py", line 233, in setup
File "cyberghostvpn.py", line 84, in createAccount
File "libs/config.py", line 90, in getConfig
Exception: The section "account" is missing configuration file!
```

**Comment by NDRBAX** [comment]
I am on Fedora 36 and had the same error message when installing and configuring. 

What I did to solve it: 

1 - on the cyberghostvpn personal space > VPN > Manage Devices: remove CyberGhost VPN for Linux 

2 - Download Hub > CyberGhost VPN for Linux  > Download again 

3 - Remove the version check in install.sh 

4 - Uninstall the version of cyberghost vpn that was installed incorrectly 

5 - Reinstall the previously downloaded version 

6 - Reboot 

Everything works again!

**Comment by Cyb10101** [comment]
I don't know what surprises me more that someone actually reads my notes or that I created an issue. 😊
I downloaded the package for Ubuntu and sadly didn't look at Fedora. But thanks for sharing, someone else may need the information later.

Unfortunately, this still doesn't work properly on Ubuntu, so I fixed it myself by hand. At least if you can call it that.

I pointed this out to CyberGhost and also sent my changes. The company didn't seem to care. The source code hasn't changed for 2 years either, so no update. Strictly speaking, that's definitely not my job. 😒

Anyway, in case someone stumbles across it and you want to fix it...
It's just the installer, but I'm not an expert, you should know what you're doing.

Download CyberGhost VPN archive for Ubuntu 20.04 (cyberghostvpn-ubuntu-20.04-1.3.4) and execute this commands:

```bash
# Extract archive
unzip cyberghostvpn-ubuntu-20.04-1.3.4.zip
cd cyberghostvpn-ubuntu-20.04-1.3.4

# Download patch files
wget https://raw.githubusercontent.com/Cyb10101/notes/master/Bugfix/2022-08-11_cyberghostvpn-ubuntu-20.04-1.3.4/1-remove-whitespace.patch
wget https://raw.githubusercontent.com/Cyb10101/notes/master/Bugfix/2022-08-11_cyberghostvpn-ubuntu-20.04-1.3.4/2-fix-installer.patch

# Patch: Change tab indent, removes trailing white space
patch install.sh < 1-remove-whitespace.patch

# Patch: Changes to fix installer
patch install.sh < 2-fix-installer.patch
```

If the original install.sh file are lost, see in folder:
https://github.com/Cyb10101/notes/tree/master/Bugfix/2022-08-11_cyberghostvpn-ubuntu-20.04-1.3.4

**Comment by NDRBAX** [comment]
I came across your notes while googling for a solution to my problem hahaha Glad you found a solution too
